coverage:
  status:
    project:
      default:
        target: 95%
        threshold: null
        if_not_found: success
    patch:
      default:
        target: 95%
        threshold: null
        if_not_found: success
